## Stage 1 : Gradle build produces the application executable jar
FROM gradle:7.2.0-jdk11 as builder

COPY . /home/gradle/src/
WORKDIR /home/gradle/src
RUN gradle build

## Stage 2 : Final image with JRE and application executable jar
FROM openjdk:14-alpine3.10

# Copy JAR into container image
RUN addgroup -S spring && adduser -S spring -G spring
USER spring
COPY --from=builder /home/gradle/src/build/libs/primes-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080

# Run application using executable jar application
CMD ["java", "-jar", "app.jar"]